### ISSUE TITLE
i ma fork ok ？

### ISSUE THREAD

**Issue by zanjs** [Dan503/mq-scss#3]

**Comment by Dan503** [comment]
The problem I have is that you published the plugin to npm as if it was your own work.

If you have an issue with my version of the code, you can submit a pull request to improve on it.

Don't steal my code and publish it under yourself as if it was your idea all along

**Comment by Dan503** [comment]
Thank you for deleting the media-scss GitHub repository.

I would also like it if you unpublished media-scss from npm by running `npm unpublish` since it is taking traffic away from mq-scss.

Since there is no readme data getting displayed on the npm website now and unpublishing it can break peoples build setups, I guess I can live with media-scss staying up on npm.

**Comment by zanjs** [comment]
The npm readme is update.

**Comment by Dan503** [comment]
Thank you I'm happy with that resolution :)

**Comment by Dan503** [comment]
Actually I know what the perfect way to prevent people from using media-scss is now.

Everything should be removed except for the package.json file and the readme.md file. Then the version number should be bumped up to version 2.0.0.

The readme text should say something like this:

> media-scss was an illegal copy of mq-scss.
>
> The code has been removed from npm to appease copywrite law.
>
> Please use mq-scss from now on
>
> https://www.npmjs.com/package/mq-scss

By doing this it has these affects:

- `npm install media-scss` will no longer download any important code so new users can't really use that command any more.
- It tells people why the code has been removed.
- It links to mq-scss so they know where to go to access the real version.
- It won't break any existing projects that use media-scss since those projects will only download the version 1 code.

Can you please do that for me :)
