### ISSUE TITLE
Use --save-dev instead?

### ISSUE THREAD

**Issue by picosam** [Dan503/mq-scss#4]
Hello, why aren't we using this package in the devDependencies instead of dependencies?

**Comment by Dan503** [comment]
Read this article I wrote and you will understand why I suggest saving it as a dependency rather than a dev dependency.

npm "dependencies" vs "devDependencies"
https://www.linkedin.com/pulse/npm-dependencies-vs-devdependencies-daniel-tonon

The short answer is that this affects the source code you write and saving it to the dependencies list adds it to a sort of short-list of important documentation that a developer should look up before they work on the project. It's easier for another developer if they don't have to find it amongst a sea of dev-dependencies.
